[package]
name = "thepotato97/gameanalytics-sdk"
description = "Official Roblox SDK for GameAnalytics. GameAnalytics is a free analytics platform that helps game developers understand their players' behaviour by delivering relevant insights."
version = "3.0.1"
license = "MIT"
authors = ["GameAnalytics <sdk@gameanalytics.com>"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["ExampleProject"]

[dependencies]
